### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by bbkz** [wger-project/helm-charts#10]
I use arm64 for my little cluster, the bitnami chart's don't (and never will) support arm64. Also they don't use the offical image provided by the PostgreSQL and Redis, they often support arm64.

Therefore i suggest using the charts from `groundhog2k`, he is using the upstream images:

* [groundhog2k PostgreSQL chart](https://github.com/groundhog2k/helm-charts/tree/master/charts/postgres)
* [groundhog2k Redis chart](https://github.com/groundhog2k/helm-charts/tree/master/charts/redis)

I already created a branch for arm64 support in my fork, if wanted i can create a pull request:

* https://github.com/bbkz/wger-helm-charts/tree/arm64

Yours,
bbk

**Comment by bbkz** [comment]
The groundhog2k is just providing the helm charts, the actual images used are the regular ones from postgres/redis and they support arm/v7. I am using these on my cluster with the charts from groundhog2k.

Using the charts as dependencies from someone else may make it simpler as we wouldn't have to maintain these as well and can rely on them.

**Comment by bbkz** [comment]
merged #14

**Comment by rolandgeider** [comment]
You're on fire 😄😄
