### ISSUE TITLE
Update dependacies

### ISSUE THREAD

**Issue by ninjatec** [wger-project/helm-charts#11]
Postre and redis dependencies in the chart are outdated.

my local testing shows the helm chart works with the latest releases.

I suggest updating

**Comment by rolandgeider** [comment]
in the docker compose setup we are using postgres 15, would suggest using the same here

**Comment by bbkz** [comment]
I am looking into this. Also i am thinking about linking the charts appversion to the docker image tag:

* [Chart.yaml#L4](https://github.com/wger-project/helm-charts/blob/master/charts/wger/Chart.yaml#L4)

This means it will always pull the `:XX-dev` image and not the `:latest`. What do you think?

**Comment by ninjatec** [comment]
I agree this should be implemented, it protects against breaking changes, a new code version should require a upgrade to the helm chart, without this it would be possible to upgrade the app inadvertently through a pod scaling or restarting

**Comment by rolandgeider** [comment]
just to be clear, the 2.1 is the used wger version, right?

In this case we would need to think about to handle them in the future. While we do have version numbers, this is a de-facto rolling release

**Comment by rolandgeider** [comment]
currently when we build the docker images we tag them as `latest` as well as `2.2-dev`. Once we release 2.2, we would start tagging them `2.3-dev` and so on

**Comment by bbkz** [comment]
ok. but does that mean there is no 2.2 docker image once it is released?

**Comment by rolandgeider** [comment]
I mean, the last 2.2 would be the "real" 2.2 since it would not change after that point and the development of 2.3 would start after that point

**Comment by bbkz** [comment]
ah.. right... i need to turn on my brain. Now i understand it.

**Comment by bbkz** [comment]
Then we should keep it on the latest and the helm users can define in their `values.yaml` a fixed version if they like to.

**Comment by ninjatec** [comment]
This is the pattern I normally see.

A helm version has a fixed app version e.g.

1.4 helm will always get 2.2 of wger (unless we override via values)

when 2.3 is released then the would require a new build of the helm so:-

1.5 helm = 2.3 of wger

But its not a hill I want to die on

**Comment by rolandgeider** [comment]
yeah but "2.2" is also not really stable since it changes with time. 

We can also discuss making releases more often, though 🤷🏻‍♂️

**Comment by bbkz** [comment]
Also i can imagine if there is a serious bug in the 2.1-dev there is no way of backporting this as of the rolling release...

**Comment by rolandgeider** [comment]
not at the moment, no

**Comment by ninjatec** [comment]
Okay then I agree.

**Comment by bbkz** [comment]
We could use the "released" `XX-dev` tags (current -1) and if there are serious bugs a new wger release could be generated...?

**Comment by rolandgeider** [comment]
I would **strongly** suggest using 2.2, this is also what's being used on the "official" wger.de server and is where all the bug reports from users get fixed. Also, I'm not sure how well 2.1 would play with the current server for things like syncronizing exercises, etc.

**Comment by bbkz** [comment]
Ok. ;-) Then i'll keep it on the latest. Thank's for the clarifications.
