### ISSUE TITLE
`app.global.image.PullPolicy` set to `IfNotPresent` or `Always`

### ISSUE THREAD

**Issue by bbkz** [wger-project/helm-charts#21]
When `app.global.image.PullPolicy` will be set to `IfNotPresent` and the `latest` docker image tag will be used, it will not upgrade the image when a new `latest` is released.

This can be a good thing to keep it a bit more stable, but can also be a problem when one node running `latest:X` and a other one `latest:Y`. Keeping it on `Always` has the downside that it always downloads the image when the pod is restarted, which then upgrades the app.

As wger is developed in a rolling release manner, i wonder what is best here to set.

Shall it be `IfNotPresent` or `Always`?

**Comment by rolandgeider** [comment]
Is there some command to manually pull new images? This would be similar to how the compose setup works where users need to do a `docker compose pull` to upgrade

**Comment by bbkz** [comment]
Not that i am aware of. It would be possible the workflow would be kind of complicated, normally we upgrade which changing the tag of the image, then it gets automatically downloaded and the pod get's replaced when the new pod runs, if it doesn't start the old pod keeps running.

`Always` means it will pull the image when the pod get's deleted
`IfNotPresent` will pull the image when the pod get's deleted when it is not present on the node it tries to start the app

Often we don't explicit tell the pod on which node it shall start, so k8s will take care of it's ressources, this means it is random which node get's the pod.

So when we have the pod running stable for a year and delete it it could start on a node which has the :latest from a year ago.

So, i think we need to set `Always` as it was set and upgrades must/will happen deleting the pod.

**Comment by bbkz** [comment]
I put `Always` as `imagePullPolicy` and added a note in the Readme, with

```bash
kubectl -n wger rollout restart deploy wger-app
```

We get at least the feature that the old pod keeps running till the new one is started. Still a unexpected upgrade can happen when a pod crashed or gets deleted, but maybe for a rolling release this is ok...
