### ISSUE TITLE
Axes behind reverse proxy

### ISSUE THREAD

**Issue by bbkz** [wger-project/helm-charts#23]
When axes is enabled and as we normally run wger behind a reverse proxy, the `real ip` must be provided somehow. For this to work the cluster must be setup to provide this.

But finally also axes must listen for this:

* https://django-axes.readthedocs.io/en/latest/4_configuration.html#configuring-reverse-proxies

Otherwise wger will be offline.

**Comment by rolandgeider** [comment]
yes, you are right! While in the docker config we do sert the X_FORWARDED_FOR header, we also need to configure axes to actually listen to it...
