### ISSUE TITLE
Redis service volume

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/helm-charts#32]
Just a heads up @bbkz , the redis service has its own volume now (was creating an unnamed one on every startup otherwise). I'm guessing that `persistent-volume-claim.yaml` and so on should be edited but I would leave the details to the professionals 😄 

https://github.com/wger-project/docker/commit/0cd9daf9bce3e479ba724145fc98062ad118f4c2

**Comment by bbkz** [comment]
Cool. The helm chart for redis we are using is already supporting persistent storages.

* https://github.com/wger-project/helm-charts/blob/master/charts/wger/values.yaml#L142

The user can ether use a manually created (existing) volume when setting `redis.storage.persistentVolumeClaimName` in his `values.yaml` or let the chart autocreate a `PVC`, depending on the clusters storage setup this will autocreate the volume.

**Comment by rolandgeider** [comment]
Ah great
