### ISSUE TITLE
Add celery images

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/helm-charts#4]
Hey @sedadas and @InputObject2 ,

we're adding some celery workers to the docker compose file, at the moment only to download ingredient images, later to sync data from fitbit or similar services: https://github.com/wger-project/docker/blob/feature/celery/docker-compose.yml#L76 

What exactly do I need to add here so that everything works? (only `celery_beat` and `celery_worker` are important, `celery_flower` is only a monitor tool)

**Comment by InputObject2** [comment]
I'll take a stab at it. The gist of it is that we will probably copy the deployment for wger and just replace the images for the ones you use with Celery.

**Comment by bbkz** [comment]
As i did quite a lot of changes, i will work on this to finalize helm version 1.4. Hope that's ok.
