### ISSUE TITLE
Database migration fails 

### ISSUE THREAD

**Issue by joaodss2** [wger-project/helm-charts#54]
Postgress extraScript needs to run manually so that wger-app can create database on postgres

Temporary solution:  
run on postgres pod with postgress user
 ```
ALTER USER wger WITH SUPERUSER;
```
change wger to user under Values.postgres.userDatabase.name

**Comment by bbkz** [comment]
Thank's for the report. Did i understood it right, the extraScript was not run in your case?

**Comment by joaodss2** [comment]
it did run but the command fails on postgres, thus not giving admin rights to the user account, which then fails the migration due to insufficient rights.
I was able to fix the issue running the command locally

**Comment by bbkz** [comment]
Ok, thank you for clarifying. I'll check that.
